export type KnowledgeKind = "Dúvida rápida" | "Pergunta frequente" | "Artigo de ajuda";
export type KnowledgeSection = { title: string; paragraphs?: string[]; steps?: string[]; links?: { label: string; href: string }[]; tone?: "info" | "warning" | "allowed" | "prohibited"; icon?: "cloud" | "check" | "warning" | "stop" };
export type KnowledgeItem = { id: string; slug?: string; kind: KnowledgeKind; category: string; title: string; summary: string; body?: string[]; sections?: KnowledgeSection[]; bodyHtml?: string };
export type KnowledgeEntry = { id: string; slug: string | null; kind: "faq" | "answer" | "article"; title: string; summary: string; body_html: string; category: string; audiences: string[]; active: boolean; position: number; featured_position: number | null; created_at: string | null; updated_at: string | null; published_at: string | null };
export const knowledgeCategories = ["Geral", "Solicitação", "Análise", "Ficha", "Autodepósito", "Atendimento", "Administração"] as const;
const escapeHtml = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
export const articleHtml = (article: KnowledgeItem) => article.sections?.map((section) => `<section class="knowledge-card${section.tone ? ` knowledge-card--${section.tone}` : ""}"><h2><span class="knowledge-card__icon" aria-hidden="true">${section.icon === "check" ? "✓" : section.icon === "warning" ? "!" : section.icon === "stop" ? "×" : "☁"}</span>${escapeHtml(section.title)}</h2>${section.paragraphs?.map((paragraph) => `<p>${escapeHtml(paragraph)}</p>`).join("") ?? ""}${section.steps ? `<ol class="knowledge-steps">${section.steps.map((step) => `<li><p>${escapeHtml(step)}</p></li>`).join("")}</ol>` : ""}${section.links?.map((link) => `<p class="knowledge-card__link"><a href="${escapeHtml(link.href)}">${escapeHtml(link.label)}</a></p>`).join("") ?? ""}</section>`).join("") ?? "";
export function initialKnowledgeEntries(faqs: { id: string; question: string; answer: string; active: boolean; position: number; featured_position?: number | null; created_at?: string; updated_at?: string }[] = []): KnowledgeEntry[] {
  return [...faqs.map((faq) => ({ id: `legacy-${faq.id}`, slug: null, kind: "faq" as const, title: faq.question, summary: faq.answer, body_html: `<p>${escapeHtml(faq.answer)}</p>`, category: "Geral", audiences: ["public", "student", "cataloger", "administrator", "panel"], active: faq.active, position: faq.position, featured_position: faq.featured_position ?? null, created_at: faq.created_at ?? null, updated_at: faq.updated_at ?? null, published_at: faq.active ? faq.created_at ?? null : null })), ...quickDoubts.map((item, index) => ({ id: `initial-${item.id}`, slug: null, kind: "answer" as const, title: item.title, summary: item.summary, body_html: `<p>${escapeHtml(item.summary)}</p>`, category: item.category, audiences: ["public", "student", "panel"], active: true, position: 1000 + index * 10, featured_position: null, created_at: null, updated_at: null, published_at: null })), ...helpArticles.map((item, index) => ({ id: `initial-${item.id}`, slug: item.slug ?? null, kind: "article" as const, title: item.title, summary: item.summary, body_html: articleHtml(item), category: item.category, audiences: ["public", "student", "panel"], active: true, position: 1100 + index * 10, featured_position: null, created_at: null, updated_at: null, published_at: null }))];
}

export const quickDoubts: KnowledgeItem[] = [
  { id: "doubt-work-upload", kind: "Dúvida rápida", category: "Solicitação", title: "Preciso enviar o PDF do trabalho?", summary: "Não. Informe um link público para o trabalho final; o PDF completo não é enviado ao Pronto!." },
  { id: "doubt-card-download", kind: "Dúvida rápida", category: "Ficha", title: "Quando a ficha fica disponível?", summary: "Após a homologação pela biblioteca e a aprovação do Nada Consta." },
];

export const helpArticles: KnowledgeItem[] = [
  { id: "article-public-link", slug: "compartilhar-link-publico", kind: "Artigo de ajuda", category: "Solicitação", title: "Como compartilhar o link público do trabalho", summary: "Passo a passo para criar um link que permita à biblioteca abrir o PDF sem pedir acesso.", sections: [
    { title: "Antes de compartilhar", tone: "info", icon: "cloud", paragraphs: ["Use o PDF final do trabalho e compartilhe somente esse arquivo, ou uma pasta criada apenas para ele. Um link público permite que qualquer pessoa que o receba abra o conteúdo; não compartilhe uma pasta com outros documentos." ] },
    { title: "Permissões corretas", tone: "allowed", icon: "check", paragraphs: ["Permita o acesso a qualquer pessoa com o link e escolha somente visualização. Teste o endereço em uma janela privada antes de informá-lo no formulário."] },
    { title: "Evite estas configurações", tone: "prohibited", icon: "stop", paragraphs: ["Não use convite limitado ao seu e-mail ou à UFBA. Não permita edição. Não configure senha, código ou prazo de expiração para o link. Se a organização bloquear o compartilhamento público, use outro serviço permitido."] },
    { title: "Google Drive", tone: "info", icon: "cloud", steps: ["Selecione o PDF e clique em Compartilhar.", "Em Acesso geral, abra a lista de permissões e escolha Qualquer pessoa com o link.", "Defina o papel como Leitor (Viewer), sem permissão de edição.", "Clique em Copiar link e depois em Concluído."], links: [{ label: "Instruções oficiais do Google Drive", href: "https://support.google.com/docs/answer/2494822?hl=pt-BR" }] },
    { title: "Microsoft OneDrive", tone: "info", icon: "cloud", steps: ["Selecione o PDF e clique em Compartilhar.", "Abra as configurações do link (ícone de engrenagem) e escolha Qualquer pessoa.", "Desative Permitir edição; mantenha somente visualização.", "Clique em Aplicar e depois em Copiar link."], paragraphs: ["Em contas institucionais, a opção Qualquer pessoa pode estar bloqueada pelo administrador. Se não aparecer, escolha outro serviço permitido."], links: [{ label: "Instruções oficiais do OneDrive", href: "https://support.microsoft.com/en-us/onedrive/share-files-and-folders-in-onedrive" }] },
    { title: "Dropbox", tone: "info", icon: "cloud", steps: ["Passe o cursor sobre o PDF e clique em Compartilhar.", "Clique em Copiar link e abra Gerenciar (Manage) nas opções do link.", "Escolha Link para visualização (Link for viewing), sem edição.", "Copie o link de visualização."], links: [{ label: "Instruções oficiais do Dropbox", href: "https://help.dropbox.com/share/create-and-share-link" }] },
    { title: "iCloud Drive", tone: "info", icon: "cloud", steps: ["No iCloud Drive, abra o menu do PDF e escolha Compartilhar.", "Em quem pode acessar, escolha Qualquer pessoa com o link.", "Em permissões, escolha Somente visualizar e baixar.", "Crie o link e clique em Copiar link."], links: [{ label: "Instruções oficiais do iCloud Drive", href: "https://support.apple.com/guide/icloud/mm708256356b/icloud" }] },
    { title: "Proton Drive", tone: "info", icon: "cloud", steps: ["Selecione o PDF e clique no ícone Compartilhar.", "Ative Criar link público (Create public link).", "Escolha Visualizador (Viewer), não Editor.", "Clique em Copiar link."], paragraphs: ["Não ative senha ou data de expiração: a biblioteca precisa conseguir abrir o arquivo pelo link."], links: [{ label: "Instruções oficiais do Proton Drive", href: "https://proton.me/support/drive-shareable-link" }] },
    { title: "Nextcloud", tone: "info", icon: "cloud", steps: ["Na lista de arquivos, selecione o PDF e abra Compartilhar.", "Crie um link público (public link).", "Escolha Somente leitura (read only), sem edição ou envio de arquivos.", "Copie o link público."], paragraphs: ["As opções variam conforme a configuração do servidor Nextcloud. Se o compartilhamento por link estiver desativado, contate o administrador ou use outro serviço permitido."], links: [{ label: "Manual oficial do Nextcloud sobre compartilhamento", href: "https://docs.nextcloud.com/server/stable/user_manual/en/files/sharing.html" }] },
    { title: "Teste o link antes de enviar", tone: "allowed", icon: "check", steps: ["Abra uma janela anônima ou privada do navegador, sem entrar na conta do serviço.", "Cole o link e confirme que o PDF abre sem pedir login, autorização, senha ou código enviado por e-mail.", "Confira se o PDF exibido é a versão final e está completo.", "Volte ao formulário, cole o endereço iniciado por https:// no campo Link público do trabalho completo e envie a solicitação."] },
    { title: "Se o teste falhar", tone: "warning", icon: "warning", paragraphs: ["Revise as permissões e gere um novo link. Não envie um endereço que abra somente para você, que peça autorização, ou que dependa de uma senha privada. O Pronto! recebe apenas o link; o PDF completo não é enviado nem armazenado pelo sistema."] },
  ] },
  { id: "article-prepare", slug: "preparar-solicitacao", kind: "Artigo de ajuda", category: "Solicitação", title: "Como preparar sua solicitação", summary: "Confira o que separar antes de iniciar o formulário.", sections: [{ title: "Antes de abrir o formulário", tone: "info", icon: "cloud", paragraphs: ["Use a versão final do trabalho, já defendida ou aprovada pela banca. Quando aplicável, ela deve incluir a folha de aprovação assinada ou digitalizada."] }, { title: "Passo a passo", tone: "allowed", icon: "check", steps: ["Hospede o arquivo em um serviço de nuvem.", "Confirme que o link funciona para qualquer pessoa.", "Separe os dados exatamente como aparecem no trabalho.", "Inicie o formulário e retome o rascunho quando precisar."] }, { title: "Atenção ao link público", tone: "warning", icon: "warning", paragraphs: ["Google Drive, OneDrive e serviços equivalentes podem ser usados. O Pronto! recebe somente o link: o PDF completo não é enviado ao sistema."] }] },
  { id: "article-corrections", slug: "corrigir-solicitacao", kind: "Artigo de ajuda", category: "Análise", title: "Como responder a uma correção da biblioteca", summary: "Entenda o que acontece quando a solicitação volta para você.", sections: [{ title: "O que significa uma correção", paragraphs: ["A biblioteca indica exatamente quais informações precisam de ajuste e explica o motivo de cada devolução."] }, { title: "Passo a passo", steps: ["Entre no painel e abra sua solicitação.", "Leia as justificativas enviadas pela biblioteca.", "Altere somente os campos disponibilizados.", "Envie novamente pelo próprio painel."] }, { title: "O que permanece protegido", paragraphs: ["Os campos que já foram conferidos ficam bloqueados. Isso preserva a revisão feita e evita que dados corretos sejam alterados por engano."] }] },
  { id: "article-deposit", slug: "concluir-autodeposito", kind: "Artigo de ajuda", category: "Autodepósito", title: "Como concluir o autodepósito", summary: "Veja o que fazer depois da liberação da ficha.", sections: [{ title: "Antes de começar", paragraphs: ["A liberação ocorre quando a ficha foi homologada e o Nada Consta aprovado. A partir daí, o guia aparece no painel."] }, { title: "Passo a passo", steps: ["Abra o guia do RI/UFBA no painel.", "Reaproveite os metadados homologados.", "Faça o depósito e escolha a licença no Repositório Institucional.", "Informe a URL permanente ou Handle à biblioteca."] }, { title: "Importante", paragraphs: ["O Pronto! orienta o processo, mas o depósito e as escolhas no RI/UFBA continuam sendo realizados por você."] }] },
];

export function normalizeKnowledge(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase(); }
export function knowledgeText(item: KnowledgeItem) { return `${item.title} ${item.summary} ${item.body?.join(" ") ?? ""} ${item.sections?.flatMap((section) => [section.title, ...(section.paragraphs ?? []), ...(section.steps ?? [])]).join(" ") ?? ""}`; }
