export type KnowledgeKind = "Dúvida rápida" | "Pergunta frequente" | "Artigo de ajuda";
export type KnowledgeSection = { title: string; paragraphs?: string[]; steps?: string[] };
export type KnowledgeItem = { id: string; slug?: string; kind: KnowledgeKind; category: string; title: string; summary: string; body?: string[]; sections?: KnowledgeSection[]; bodyHtml?: string };
export type KnowledgeEntry = { id: string; slug: string | null; kind: "faq" | "answer" | "article"; title: string; summary: string; body_html: string; category: string; audiences: string[]; active: boolean; position: number; featured_position: number | null; created_at: string | null; updated_at: string | null; published_at: string | null };
export const knowledgeCategories = ["Geral", "Solicitação", "Análise", "Ficha", "Autodepósito", "Atendimento", "Administração"] as const;
const escapeHtml = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
export const articleHtml = (article: KnowledgeItem) => article.sections?.map((section) => `<h2>${escapeHtml(section.title)}</h2>${section.paragraphs?.map((paragraph) => `<p>${escapeHtml(paragraph)}</p>`).join("") ?? ""}${section.steps ? `<ol>${section.steps.map((step) => `<li><p>${escapeHtml(step)}</p></li>`).join("")}</ol>` : ""}`).join("") ?? "";
export function initialKnowledgeEntries(faqs: { id: string; question: string; answer: string; active: boolean; position: number; featured_position?: number | null; created_at?: string; updated_at?: string }[] = []): KnowledgeEntry[] {
  return [...faqs.map((faq) => ({ id: `legacy-${faq.id}`, slug: null, kind: "faq" as const, title: faq.question, summary: faq.answer, body_html: `<p>${escapeHtml(faq.answer)}</p>`, category: "Geral", audiences: ["public", "student", "cataloger", "administrator", "panel"], active: faq.active, position: faq.position, featured_position: faq.featured_position ?? null, created_at: faq.created_at ?? null, updated_at: faq.updated_at ?? null, published_at: faq.active ? faq.created_at ?? null : null })), ...quickDoubts.map((item, index) => ({ id: `initial-${item.id}`, slug: null, kind: "answer" as const, title: item.title, summary: item.summary, body_html: `<p>${escapeHtml(item.summary)}</p>`, category: item.category, audiences: ["public", "student", "panel"], active: true, position: 1000 + index * 10, featured_position: null, created_at: null, updated_at: null, published_at: null })), ...helpArticles.map((item, index) => ({ id: `initial-${item.id}`, slug: item.slug ?? null, kind: "article" as const, title: item.title, summary: item.summary, body_html: articleHtml(item), category: item.category, audiences: ["public", "student", "panel"], active: true, position: 1100 + index * 10, featured_position: null, created_at: null, updated_at: null, published_at: null }))];
}

export const quickDoubts: KnowledgeItem[] = [
  { id: "doubt-work-upload", kind: "Dúvida rápida", category: "Solicitação", title: "Preciso enviar o PDF do trabalho?", summary: "Não. Informe um link público para o trabalho final; o PDF completo não é enviado ao Pronto!." },
  { id: "doubt-card-download", kind: "Dúvida rápida", category: "Ficha", title: "Quando a ficha fica disponível?", summary: "Após a homologação pela biblioteca e a aprovação do Nada Consta." },
];

export const helpArticles: KnowledgeItem[] = [
  { id: "article-prepare", slug: "preparar-solicitacao", kind: "Artigo de ajuda", category: "Solicitação", title: "Como preparar sua solicitação", summary: "Confira o que separar antes de iniciar o formulário.", sections: [{ title: "Antes de abrir o formulário", paragraphs: ["Use a versão final do trabalho, já defendida ou aprovada pela banca. Quando aplicável, ela deve incluir a folha de aprovação assinada ou digitalizada."] }, { title: "Passo a passo", steps: ["Hospede o arquivo em um serviço de nuvem.", "Confirme que o link funciona para qualquer pessoa.", "Separe os dados exatamente como aparecem no trabalho.", "Inicie o formulário e retome o rascunho quando precisar."] }, { title: "Atenção ao link público", paragraphs: ["Google Drive, OneDrive e serviços equivalentes podem ser usados. O Pronto! recebe somente o link: o PDF completo não é enviado ao sistema."] }] },
  { id: "article-corrections", slug: "corrigir-solicitacao", kind: "Artigo de ajuda", category: "Análise", title: "Como responder a uma correção da biblioteca", summary: "Entenda o que acontece quando a solicitação volta para você.", sections: [{ title: "O que significa uma correção", paragraphs: ["A biblioteca indica exatamente quais informações precisam de ajuste e explica o motivo de cada devolução."] }, { title: "Passo a passo", steps: ["Entre no painel e abra sua solicitação.", "Leia as justificativas enviadas pela biblioteca.", "Altere somente os campos disponibilizados.", "Envie novamente pelo próprio painel."] }, { title: "O que permanece protegido", paragraphs: ["Os campos que já foram conferidos ficam bloqueados. Isso preserva a revisão feita e evita que dados corretos sejam alterados por engano."] }] },
  { id: "article-deposit", slug: "concluir-autodeposito", kind: "Artigo de ajuda", category: "Autodepósito", title: "Como concluir o autodepósito", summary: "Veja o que fazer depois da liberação da ficha.", sections: [{ title: "Antes de começar", paragraphs: ["A liberação ocorre quando a ficha foi homologada e o Nada Consta aprovado. A partir daí, o guia aparece no painel."] }, { title: "Passo a passo", steps: ["Abra o guia do RI/UFBA no painel.", "Reaproveite os metadados homologados.", "Faça o depósito e escolha a licença no Repositório Institucional.", "Informe a URL permanente ou Handle à biblioteca."] }, { title: "Importante", paragraphs: ["O Pronto! orienta o processo, mas o depósito e as escolhas no RI/UFBA continuam sendo realizados por você."] }] },
];

export function normalizeKnowledge(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase(); }
export function knowledgeText(item: KnowledgeItem) { return `${item.title} ${item.summary} ${item.body?.join(" ") ?? ""} ${item.sections?.flatMap((section) => [section.title, ...(section.paragraphs ?? []), ...(section.steps ?? [])]).join(" ") ?? ""}`; }
