import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const migration=readFileSync("supabase/migrations/202608230009_administration_operations.sql","utf8");
const candidateMigration=readFileSync("supabase/migrations/202608310000_staff_candidate_selection.sql","utf8");
const page=readFileSync("src/components/admin-operations.tsx","utf8");
const faqMigration=readFileSync("supabase/migrations/202608260002_frequently_asked_questions.sql","utf8");
const footer=readFileSync("src/components/site-footer.tsx","utf8");
const shell=readFileSync("src/components/dashboard-shell.tsx","utf8");
test("admin operations are enforced and audited in PostgreSQL",()=>{assert.match(migration,/active_administrator_required/g);assert.match(migration,/administrator_cannot_remove_own_access/);assert.match(migration,/account_administration_changed/);assert.match(migration,/program_operation_configuration_changed/)});
test("blocked and inactive accounts cannot be bypassed by UI-only rules",()=>{assert.match(migration,/target_status public\.account_status/);assert.match(migration,/update public\.profiles set role=target_role,status=target_status/)});
test("dashboard covers all operational deliveries",()=>{for(const text of ["Contas e perfis","Coordenações, Magic Link, guia e SLA","Mural, status e calendário","Templates básicos","Estatísticas e exportação","Expurgo do Nada Consta","Logs operacionais"])assert.match(page,new RegExp(text))});
test("exports stay client-side and do not expose secrets",()=>{assert.match(page,/Exportar CSV/);assert.match(page,/Exportar JSON/);assert.doesNotMatch(page,/service_role|SUPABASE_SERVICE/)});
test("admin selects confirmed institutional accounts without handling UUIDs",()=>{assert.doesNotMatch(page,/UUID confirmado/);assert.match(page,/Conta institucional/);assert.match(page,/staffCandidates\.map/);assert.match(candidateMigration,/current_user_role\(\).*administrator/s);assert.match(candidateMigration,/email_confirmed_at is not null/);assert.match(candidateMigration,/not exists[\s\S]*public\.profiles/);});
test("admin uses horizontal tabs and manages public frequently asked questions",()=>{assert.match(page,/role="tablist"/);assert.match(page,/Perguntas frequentes/);assert.match(page,/admin_save_frequently_asked_question/);assert.match(faqMigration,/frequently_asked_questions_public_read/);assert.match(faqMigration,/active_administrator_required/);assert.match(faqMigration,/frequently_asked_question_saved/)});
test("shared shell greets the user and footer publishes version, credits and source",()=>{assert.match(shell,/Olá, \{firstName\}/);assert.match(footer,/Beta/);assert.match(footer,/2026/);assert.match(footer,/vibe coding/);assert.match(footer,/openai\.com\/pt-BR\/codex/);assert.match(footer,/AGPL-3\.0/);assert.match(footer,/github\.com\/ramondavi\/codex-projetos/)});
