import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const migration=readFileSync("supabase/migrations/202608230009_administration_operations.sql","utf8");
const candidateMigration=readFileSync("supabase/migrations/202608310000_staff_candidate_selection.sql","utf8");
const page=readFileSync("src/components/admin-operations.tsx","utf8");
const faqMigration=readFileSync("supabase/migrations/202608260002_frequently_asked_questions.sql","utf8");
const knowledgeMigration=readFileSync("supabase/migrations/202609220001_knowledge_base.sql","utf8");
const knowledgeEditor=readFileSync("src/components/knowledge-base-admin.tsx","utf8");
const footer=readFileSync("src/components/site-footer.tsx","utf8");
const shell=readFileSync("src/components/dashboard-shell.tsx","utf8");
const helpWidget=readFileSync("src/components/backend-help-widget.tsx","utf8");
test("admin operations are enforced and audited in PostgreSQL",()=>{assert.match(migration,/active_administrator_required/g);assert.match(migration,/administrator_cannot_remove_own_access/);assert.match(migration,/account_administration_changed/);assert.match(migration,/program_operation_configuration_changed/)});
test("blocked and inactive accounts cannot be bypassed by UI-only rules",()=>{assert.match(migration,/target_status public\.account_status/);assert.match(migration,/update public\.profiles set role=target_role,status=target_status/)});
test("dashboard covers all operational deliveries",()=>{for(const text of ["Equipe e acessos","Programas, coordenações e SLA","Calendário e comunicados da biblioteca","Pendências e respostas padrão","Indicadores e exportação","Arquivos e retenção","Auditoria operacional"])assert.match(page,new RegExp(text))});
test("exports stay client-side and do not expose secrets",()=>{assert.match(page,/Exportar CSV/);assert.match(page,/Exportar JSON/);assert.doesNotMatch(page,/service_role|SUPABASE_SERVICE/)});
test("admin selects confirmed institutional accounts without handling UUIDs",()=>{assert.doesNotMatch(page,/UUID confirmado/);assert.match(page,/Conta institucional/);assert.match(page,/staffCandidates\.map/);assert.match(candidateMigration,/current_user_role\(\).*administrator/s);assert.match(candidateMigration,/email_confirmed_at is not null/);assert.match(candidateMigration,/not exists[\s\S]*public\.profiles/);});
test("admin uses one editor for FAQs, answers and articles",()=>{assert.match(page,/role="tablist"/);assert.match(page,/<KnowledgeBaseAdmin/);assert.doesNotMatch(page,/admin_save_frequently_asked_question/);assert.match(knowledgeEditor,/RichTextEditor/);assert.match(knowledgeEditor,/admin_save_knowledge_base_entry/);assert.match(knowledgeMigration,/insert into public\.knowledge_base_entries\(kind,title,summary/);assert.match(knowledgeMigration,/active_administrator_required/);assert.match(faqMigration,/frequently_asked_questions_public_read/)});
test("shared shell greets the user and footer publishes version, credits and source",()=>{assert.match(shell,/\{t\.greeting\}, \{firstName\}/);assert.match(shell,/pt: \{[^\n]*greeting: "Olá"/);assert.match(footer,/Beta/);assert.match(footer,/2026/);assert.match(footer,/vibe coding/);assert.match(footer,/openai\.com\/pt-BR\/codex/);assert.match(footer,/AGPL-3\.0/);assert.match(footer,/github\.com\/ramondavi\/codex-projetos/)});
test("painel oferece ajuda contextual discreta",()=>{assert.match(shell,/<BackendHelpWidget role=\{role\}/);assert.match(helpWidget,/context=\$\{activeContext\}/);assert.match(helpWidget,/HelpSearch compact/);assert.match(helpWidget,/backend-help__trigger/);assert.match(helpWidget,/setSelected\(item\)/);assert.match(helpWidget,/target="_blank"/);assert.match(helpWidget,/Contextos anteriores/);assert.match(helpWidget,/Fechar ajuda contextual/)});
