import { SiteHeader } from "@/components/site-header";
import type { Metadata } from "next";
import { AppIcon } from "@/components/app-icon";
import { getInterfaceLanguage } from "@/lib/server-language";
import type { InterfaceLanguage } from "@/lib/interface-language";

export async function generateMetadata(): Promise<Metadata> {
  const t = copy[await getInterfaceLanguage()];
  return { title: t.intro[0], description: t.intro[2], alternates: { canonical: "/acessibilidade" }, openGraph: { title: `${t.intro[0]} | Pronto!`, description: t.intro[2], url: "/acessibilidade", images: [{ url: "/opengraph-image", alt: `${t.intro[0]} | Pronto!` }] }, twitter: { title: `${t.intro[0]} | Pronto!`, description: t.intro[2], images: ["/opengraph-image"] } };
}

const copy: Record<InterfaceLanguage, { intro: [string, string, string]; resources: [string, string][]; labels: [string, string, string, string]; shortcuts: string[]; note: string; view: [string, string]; sign: [string, string]; barrier: [string, string] }> = {
  pt: { intro: ["Acessibilidade digital", "Um Pronto! mais simples de usar.", "O Pronto! foi construído para funcionar com teclado, diferentes tamanhos de texto, contraste elevado e tecnologias assistivas."], resources: [["Navegação por teclado", "Use Tab, Enter e Espaço para percorrer e acionar todos os controles."], ["Visualização ajustável", "A barra superior permite ampliar texto e ativar alto contraste neste navegador."], ["Encontrou uma barreira?", "Escreva para bibarq@ufba.br, indicando a página e o que tentou fazer."]], labels: ["Recursos principais de acessibilidade", "Atalhos e detalhes de acessibilidade", "Recursos disponíveis", "Atalhos e recursos"], shortcuts: ["vai direto ao conteúdo principal.", "vai ao menu principal.", "abre a Central de ajuda.", "abre esta página.", "abre a Política de privacidade."], note: "Em alguns navegadores, o atalho pode incluir Shift ou outra tecla adicional. Os links e botões também podem ser usados normalmente com Tab, Enter e Espaço.", view: ["Visualização", "A barra no topo oferece controles para aumentar ou reduzir o texto e para ativar alto contraste. Essas preferências ficam salvas apenas neste navegador."], sign: ["Libras", "Quando a Barra Brasil oficial está ativa, o recurso VLibras é disponibilizado por ela. O Pronto! não coleta dados desse recurso."], barrier: ["Encontrou uma barreira?", "Conte para a Biblioteca da Faculdade de Arquitetura, descrevendo a página e o que tentou fazer. Vamos analisar e buscar uma solução."] },
  en: { intro: ["Digital accessibility", "Pronto! made easier to use.", "Pronto! works with keyboards, different text sizes, high contrast and assistive technology."], resources: [["Keyboard navigation", "Use Tab, Enter and Space to reach and activate every control."], ["Adjustable display", "Use the top bar to enlarge text and enable high contrast in this browser."], ["Found a barrier?", "Email bibarq@ufba.br with the page and what you tried to do."]], labels: ["Main accessibility features", "Accessibility shortcuts and details", "Available features", "Shortcuts and features"], shortcuts: ["goes to the main content.", "goes to the main menu.", "opens the Help center.", "opens this page.", "opens the Privacy policy."], note: "Some browsers also require Shift or another key. Links and buttons work with Tab, Enter and Space.", view: ["Display", "Use the top bar to change text size and enable high contrast. These preferences are saved only in this browser."], sign: ["Brazilian Sign Language", "When the official Barra Brasil is active, it provides VLibras. Pronto! does not collect data from this feature."], barrier: ["Found a barrier?", "Tell the Faculty of Architecture Library which page you used and what you tried to do. We will investigate and seek a solution."] },
  es: { intro: ["Accesibilidad digital", "Un Pronto! más fácil de usar.", "Pronto! funciona con teclado, distintos tamaños de texto, alto contraste y tecnologías de asistencia."], resources: [["Navegación con teclado", "Use Tab, Intro y Espacio para acceder a todos los controles."], ["Visualización ajustable", "Use la barra superior para ampliar el texto y activar el alto contraste."], ["¿Encontró una barrera?", "Escriba a bibarq@ufba.br e indique la página y lo que intentó hacer."]], labels: ["Funciones principales de accesibilidad", "Atajos y detalles de accesibilidad", "Funciones disponibles", "Atajos y funciones"], shortcuts: ["va al contenido principal.", "va al menú principal.", "abre el Centro de ayuda.", "abre esta página.", "abre la Política de privacidad."], note: "Algunos navegadores requieren Shift u otra tecla. Los enlaces y botones funcionan con Tab, Intro y Espacio.", view: ["Visualización", "Use la barra superior para cambiar el tamaño del texto y activar el alto contraste. Estas preferencias se guardan solo en este navegador."], sign: ["Lengua de señas brasileña", "Cuando la Barra Brasil oficial está activa, ofrece VLibras. Pronto! no recopila datos de esta función."], barrier: ["¿Encontró una barrera?", "Indique a la Biblioteca de la Facultad de Arquitectura la página y lo que intentó hacer. Investigaremos y buscaremos una solución."] },
  de: { intro: ["Digitale Barrierefreiheit", "Pronto! einfacher nutzen.", "Pronto! unterstützt Tastaturbedienung, verschiedene Schriftgrößen, hohen Kontrast und assistive Technologien."], resources: [["Tastaturnavigation", "Mit Tab, Eingabe und Leertaste erreichen Sie alle Bedienelemente."], ["Anpassbare Ansicht", "In der oberen Leiste können Sie Text vergrößern und hohen Kontrast aktivieren."], ["Barriere gefunden?", "Schreiben Sie an bibarq@ufba.br und nennen Sie die Seite und Ihren Versuch."]], labels: ["Wichtige Funktionen zur Barrierefreiheit", "Tastenkürzel und Hinweise zur Barrierefreiheit", "Verfügbare Funktionen", "Tastenkürzel und Funktionen"], shortcuts: ["führt zum Hauptinhalt.", "führt zum Hauptmenü.", "öffnet die Hilfe.", "öffnet diese Seite.", "öffnet die Datenschutzerklärung."], note: "Manche Browser benötigen zusätzlich Shift oder eine andere Taste. Links und Schaltflächen funktionieren auch mit Tab, Eingabe und Leertaste.", view: ["Ansicht", "Die obere Leiste bietet Einstellungen für Schriftgröße und hohen Kontrast. Diese bleiben nur in diesem Browser gespeichert."], sign: ["Brasilianische Gebärdensprache", "Ist die offizielle Barra Brasil aktiv, stellt sie VLibras bereit. Pronto! erhebt keine Daten aus dieser Funktion."], barrier: ["Barriere gefunden?", "Nennen Sie der Bibliothek der Fakultät für Architektur die Seite und Ihren Versuch. Wir prüfen das Problem und suchen eine Lösung."] },
  fr: { intro: ["Accessibilité numérique", "Un Pronto! plus facile à utiliser.", "Pronto! fonctionne au clavier, avec différentes tailles de texte, un contraste élevé et les technologies d’assistance."], resources: [["Navigation au clavier", "Utilisez Tab, Entrée et Espace pour accéder aux commandes."], ["Affichage réglable", "La barre supérieure permet d’agrandir le texte et d’activer le contraste élevé."], ["Un obstacle ?", "Écrivez à bibarq@ufba.br en précisant la page et l’action tentée."]], labels: ["Principales fonctions d’accessibilité", "Raccourcis et détails d’accessibilité", "Fonctions disponibles", "Raccourcis et fonctions"], shortcuts: ["mène au contenu principal.", "mène au menu principal.", "ouvre le Centre d’aide.", "ouvre cette page.", "ouvre la Politique de confidentialité."], note: "Certains navigateurs exigent aussi Maj ou une autre touche. Les liens et boutons fonctionnent avec Tab, Entrée et Espace.", view: ["Affichage", "La barre supérieure permet de changer la taille du texte et d’activer le contraste élevé. Ces préférences restent dans ce navigateur."], sign: ["Langue des signes brésilienne", "Lorsque la Barra Brasil officielle est active, elle fournit VLibras. Pronto! ne collecte aucune donnée de cette fonction."], barrier: ["Un obstacle ?", "Indiquez à la bibliothèque de la Faculté d’architecture la page et l’action tentée. Nous examinerons le problème et chercherons une solution."] },
  it: { intro: ["Accessibilità digitale", "Un Pronto! più facile da usare.", "Pronto! funziona con la tastiera, diverse dimensioni del testo, contrasto elevato e tecnologie assistive."], resources: [["Navigazione da tastiera", "Usa Tab, Invio e Spazio per accedere ai controlli."], ["Visualizzazione regolabile", "La barra superiore permette di ingrandire il testo e attivare il contrasto elevato."], ["Hai trovato una barriera?", "Scrivi a bibarq@ufba.br indicando la pagina e cosa hai tentato di fare."]], labels: ["Principali funzioni di accessibilità", "Scorciatoie e dettagli sull’accessibilità", "Funzioni disponibili", "Scorciatoie e funzioni"], shortcuts: ["va al contenuto principale.", "va al menu principale.", "apre il Centro assistenza.", "apre questa pagina.", "apre l’Informativa sulla privacy."], note: "Alcuni browser richiedono anche Maiusc o un altro tasto. Link e pulsanti funzionano con Tab, Invio e Spazio.", view: ["Visualizzazione", "La barra superiore permette di cambiare la dimensione del testo e attivare il contrasto elevato. Queste preferenze restano solo in questo browser."], sign: ["Lingua dei segni brasiliana", "Quando la Barra Brasil ufficiale è attiva, offre VLibras. Pronto! non raccoglie dati da questa funzione."], barrier: ["Hai trovato una barriera?", "Indica alla Biblioteca della Facoltà di Architettura la pagina e cosa hai tentato di fare. Esamineremo il problema e cercheremo una soluzione."] },
};

export default async function AccessibilityPage() {
  const t = copy[await getInterfaceLanguage()];
  return <><SiteHeader /><main className="accessibility-page"><header className="container accessibility-page__hero">
    <p className="eyebrow">{t.intro[0]}</p><h1>{t.intro[1]}</h1><p>{t.intro[2]}</p>
  </header><section className="container accessibility-page__cards" aria-label={t.labels[0]}>{t.resources.map(([title, description], index) => <article key={title}><AppIcon name={(["check", "settings", "help"] as const)[index]} /><h2>{title}</h2><p>{description}</p></article>)}</section><section className="container accessibility-page__content" aria-label={t.labels[1]}><div className="accessibility-page__section-heading"><AppIcon name="help" /><div><p className="eyebrow">{t.labels[2]}</p><h2>{t.labels[3]}</h2></div></div>
    <ul>{t.shortcuts.map((description, index) => <li key={index}><strong>Alt + {index + 1}:</strong> {description}</li>)}</ul>
    <p>{t.note}</p><h2>{t.view[0]}</h2><p>{t.view[1]}</p><h2>{t.sign[0]}</h2><p>{t.sign[1]}</p><h2>{t.barrier[0]}</h2><p>{t.barrier[1]} <a href="mailto:bibarq@ufba.br">bibarq@ufba.br</a>.</p>
  </section></main></>;
}
