"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

type User={id:string;full_name:string;email:string;role:string;status:string;created_at:string;staff_profiles:{professional_name:string;crb:string}[]};
type StaffCandidate={user_id:string;email:string};
type Program={id:string;name:string;level:string;service_level_business_days:number;repository_deposit_enabled:boolean;coordination_magic_link_enabled:boolean;coordination_contacts:{name:string;email:string;active:boolean}[]};
type Announcement={id:string;type:string;title:string;message:string;starts_at:string;ends_at:string|null;active:boolean};
type Template={id:string;code:string;label:string;message:string;active:boolean;position:number};
type Faq={id:string;question:string;answer:string;active:boolean;position:number};
type Relation<T>=T[]&Partial<T>;
type Log={id:string;action:string;entity_type:string;entity_id:string|null;metadata:Record<string,unknown>;occurred_at:string;profiles:Relation<{full_name:string}>|null};
type Purge={id:string;request_id:string;object_path:string;purge_after:string;cataloging_requests:Relation<{protocol:string}>|null};
type StatItem={id?:string|null;label:string;count:number}; type Stats={total:number;by_status:StatItem[];by_program:StatItem[];by_staff:StatItem[];records:Record<string,unknown>[]};
const roleLabels:Record<string,string>={student:"Estudante",cataloger:"Catalogador",administrator:"Administrador"};
const statusLabels:Record<string,string>={active:"Ativa",blocked:"Bloqueada",inactive:"Inativa"};
const actionLabels:Record<string,string>={account_administration_changed:"Conta alterada",program_operation_configuration_changed:"Programa configurado",library_announcement_saved:"Mural atualizado",issue_template_changed:"Template alterado",frequently_asked_question_saved:"Pergunta frequente alterada",nada_consta_purged:"Nada Consta expurgado"};

export function AdminOperations(props:{users:User[];staffCandidates:StaffCandidate[];programs:Program[];announcements:Announcement[];templates:Template[];logs:Log[];purgeDocuments:Purge[];faqs:Faq[]}){
 const [message,setMessage]=useState(""); const [busy,setBusy]=useState(""); const [stats,setStats]=useState<Stats|null>(null); const [purge,setPurge]=useState(props.purgeDocuments); const [faqs,setFaqs]=useState(props.faqs); const [activeTab,setActiveTab]=useState("users");
 const supabase=createClient(); const run=async(key:string,job:()=>PromiseLike<{error:unknown}>,ok:string)=>{setBusy(key);setMessage("");const {error}=await job();setMessage(error?"Não foi possível salvar. Confira os dados e sua autorização.":ok);setBusy("");};
 async function saveUser(user:User,form:FormData){await run(`u-${user.id}`,()=>supabase.rpc("admin_manage_account",{target_profile_id:user.id,target_role:String(form.get("role")),target_status:String(form.get("status")),professional_name:String(form.get("professional_name")??""),professional_crb:String(form.get("crb")??"")}),"Conta atualizada e ação registrada no log.");}
 async function provision(form:FormData){await run("provision",()=>supabase.rpc("provision_staff_account",{target_user_id:String(form.get("id")),staff_full_name:String(form.get("full_name")),staff_professional_name:String(form.get("professional_name")),staff_crb:String(form.get("crb")),staff_role:String(form.get("role"))}),"Conta interna provisionada. Atualize a página para visualizá-la.");}
 async function saveProgram(program:Program,form:FormData){await run(`p-${program.id}`,()=>supabase.rpc("admin_configure_program",{target_program_id:program.id,sla_business_days:Number(form.get("sla")),repository_enabled:form.get("repository")==="on",coordination_enabled:form.get("coordination")==="on",contact_name:String(form.get("name")??""),contact_email:String(form.get("email")??"")}),"Programa, coordenação e SLA atualizados.");}
 async function saveAnnouncement(form:FormData){await run("announcement",()=>supabase.rpc("admin_save_announcement",{announcement_id:null,announcement_type:String(form.get("type")),announcement_title:String(form.get("title")),announcement_message:String(form.get("message")),starts_at:new Date(String(form.get("starts"))).toISOString(),ends_at:form.get("ends")?new Date(String(form.get("ends"))).toISOString():null,enabled:form.get("active")==="on"}),"Aviso publicado no mural.");}
 async function saveTemplate(template:Template,form:FormData){await run(`t-${template.id}`,()=>supabase.rpc("admin_update_issue_template",{target_template_id:template.id,template_label:String(form.get("label")),template_message:String(form.get("message")),enabled:form.get("active")==="on",template_position:Number(form.get("position"))}),"Template atualizado.");}
 async function saveFaq(faq:Faq,form:FormData){setBusy(`f-${faq.id||"new"}`);setMessage("");const payload={faq_id:faq.id||null,faq_question:String(form.get("question")),faq_answer:String(form.get("answer")),faq_position:Number(form.get("position")),enabled:form.get("active")==="on"};const {data,error}=await supabase.rpc("admin_save_frequently_asked_question",payload);if(error)setMessage("Não foi possível salvar a pergunta frequente.");else{setMessage("Pergunta frequente salva e registrada no log.");setFaqs(current=>current.map(item=>item===faq?{...item,id:String(data),question:payload.faq_question,answer:payload.faq_answer,position:payload.faq_position,active:payload.enabled}:item));}setBusy("");}
 async function loadStats(form:FormData){setBusy("stats");const start=form.get("start")?new Date(String(form.get("start"))).toISOString():null;const end=form.get("end")?new Date(`${String(form.get("end"))}T23:59:59`).toISOString():null;const {data,error}=await supabase.rpc("admin_statistics",{period_start:start,period_end:end});setStats(error?null:data as Stats);setMessage(error?"Não foi possível calcular os indicadores.":"Indicadores atualizados.");setBusy("");}
 function download(format:"json"|"csv"){if(!stats)return;let body:string,mime:string,name:string;if(format==="json"){body=JSON.stringify(stats.records,null,2);mime="application/json";name="pronto-solicitacoes.json";}else{const keys=["protocol","status","submitted_at","program","staff"];body=[keys.join(","),...stats.records.map(r=>keys.map(k=>`"${String(r[k]??"").replaceAll('"','""')}"`).join(","))].join("\n");mime="text/csv;charset=utf-8";name="pronto-solicitacoes.csv";}const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([body],{type:mime}));a.download=name;a.click();URL.revokeObjectURL(a.href);}
 async function purgeFile(doc:Purge){setBusy(`x-${doc.id}`);const removed=await supabase.storage.from("nada-consta").remove([doc.object_path]);if(removed.error){setMessage("O arquivo não pôde ser removido do Storage.");setBusy("");return;}const confirmed=await supabase.rpc("admin_confirm_nada_consta_purge",{target_document_id:doc.id});if(confirmed.error)setMessage("Arquivo removido, mas o registro de expurgo precisa ser conferido.");else{setPurge(v=>v.filter(x=>x.id!==doc.id));setMessage("Nada Consta expurgado e registro textual preservado.");}setBusy("");}
 return <div className="admin-operations" data-active-tab={activeTab}>{message&&<p className="auth-feedback" role="status">{message}</p>}<div className="admin-tabs" role="tablist" aria-label="Seções da Administração">{[["users","Usuários"],["programs","Programas"],["library","Biblioteca"],["service","Atendimento"],["faq","Perguntas frequentes"],["stats","Indicadores"],["retention","Retenção"],["audit","Auditoria"]].map(([id,label])=><button type="button" role="tab" aria-selected={activeTab===id} className={activeTab===id?"is-active":""} onClick={()=>setActiveTab(id)} key={id}>{label}</button>)}</div>
  <section className="panel admin-section"><p className="eyebrow">Usuários</p><h2>Contas e perfis</h2><p>Bloqueio e inativação interrompem a autorização imediatamente. Para incluir alguém na equipe, crie e confirme primeiro a conta institucional no Supabase; ela aparecerá na seleção abaixo.</p><form className="admin-grid admin-provision" action={provision}><label>Conta institucional<select name="id" required defaultValue=""><option value="" disabled>{props.staffCandidates.length ? "Selecione uma conta confirmada" : "Nenhuma conta disponível"}</option>{props.staffCandidates.map(candidate=><option key={candidate.user_id} value={candidate.user_id}>{candidate.email}</option>)}</select></label><label>Nome completo<input name="full_name" required/></label><label>Nome profissional<input name="professional_name" required/></label><label>CRB<input name="crb" required/></label><label>Perfil<select name="role"><option value="cataloger">Catalogador</option><option value="administrator">Administrador</option></select></label><button className="button button--primary button--small" disabled={busy==="provision"||props.staffCandidates.length===0}>Provisionar equipe</button></form><div className="admin-list">{props.users.map(u=>{const staff=u.staff_profiles?.[0];return <form className="admin-row" action={f=>saveUser(u,f)} key={u.id}><div><strong>{u.full_name}</strong><small>{u.email}</small></div><label>Perfil<select name="role" defaultValue={u.role}>{Object.entries(roleLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Situação<select name="status" defaultValue={u.status}>{Object.entries(statusLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Nome profissional<input name="professional_name" defaultValue={staff?.professional_name??""}/></label><label>CRB<input name="crb" defaultValue={staff?.crb??""}/></label><button className="button button--secondary button--small" disabled={busy===`u-${u.id}`}>Salvar</button></form>})}</div></section>
  <section className="panel admin-section"><p className="eyebrow">Programas</p><h2>Coordenações, Magic Link, guia e SLA</h2><div className="admin-list">{props.programs.map(p=>{const c=p.coordination_contacts.find(x=>x.active);return <form className="admin-row admin-row--program" action={f=>saveProgram(p,f)} key={p.id}><div><strong>{p.name}</strong><small>{p.level}</small></div><label>SLA (dias úteis)<input name="sla" type="number" min="1" max="30" defaultValue={p.service_level_business_days}/></label><label><input name="repository" type="checkbox" defaultChecked={p.repository_deposit_enabled}/> Guia RI ativo</label><label><input name="coordination" type="checkbox" defaultChecked={p.coordination_magic_link_enabled}/> Magic Link ativo</label><label>Contato<input name="name" defaultValue={c?.name??""}/></label><label>E-mail<input name="email" type="email" defaultValue={c?.email??""}/></label><button className="button button--secondary button--small" disabled={busy===`p-${p.id}`}>Salvar</button></form>})}</div></section>
  <section className="panel admin-section"><p className="eyebrow">Biblioteca</p><h2>Mural, status e calendário</h2><p>Cadastre “Feriado” ou “Ponto facultativo” para que a data apareça automaticamente no painel dos estudantes durante o mês correspondente.</p><form className="admin-grid" action={saveAnnouncement}><label>Tipo<select name="type"><option value="normal">Normal</option><option value="recess">Recesso</option><option value="strike">Paralisação/greve</option><option value="holiday">Feriado</option><option value="optional_day">Ponto facultativo</option><option value="other">Outro</option></select></label><label>Título<input name="title" required/></label><label className="admin-wide">Mensagem<textarea name="message" rows={3} required/></label><label>Início<input name="starts" type="datetime-local" required/></label><label>Fim opcional<input name="ends" type="datetime-local"/></label><label><input name="active" type="checkbox" defaultChecked/> Ativo</label><button className="button button--primary button--small">Publicar aviso</button></form>{props.announcements.map(a=><article className="admin-summary" key={a.id}><strong>{a.title}</strong><span>{a.active?"Ativo":"Inativo"} · {a.type}</span><p>{a.message}</p></article>)}</section>
  <section className="panel admin-section"><p className="eyebrow">Atendimento</p><h2>Templates básicos de pendência</h2>{props.templates.map(t=><form className="admin-row admin-row--template" action={f=>saveTemplate(t,f)} key={t.id}><code>{t.code}</code><label>Rótulo<input name="label" defaultValue={t.label}/></label><label className="admin-wide">Texto<textarea name="message" defaultValue={t.message}/></label><label>Ordem<input name="position" type="number" defaultValue={t.position}/></label><label><input name="active" type="checkbox" defaultChecked={t.active}/> Ativo</label><button className="button button--secondary button--small">Salvar</button></form>)}</section>
  <section className="panel admin-section"><p className="eyebrow">Indicadores</p><h2>Estatísticas e exportação</h2><form className="admin-grid" action={loadStats}><label>De<input name="start" type="date"/></label><label>Até<input name="end" type="date"/></label><button className="button button--primary button--small" disabled={busy==="stats"}>Calcular</button></form>{stats&&<><div className="stat-grid"><article><strong>{stats.total}</strong><span>solicitações</span></article>{stats.by_status.map(x=><article key={x.label}><strong>{x.count}</strong><span>{x.label}</span></article>)}</div><div className="admin-columns"><Metric title="Por curso/programa" items={stats.by_program}/><Metric title="Por bibliotecário" items={stats.by_staff}/></div><div className="button-row"><button className="button button--secondary button--small" onClick={()=>download("csv")}>Exportar CSV</button><button className="button button--secondary button--small" onClick={()=>download("json")}>Exportar JSON</button></div></>}</section>
  <section className="panel admin-section"><p className="eyebrow">Retenção</p><h2>Expurgo do Nada Consta</h2><p>Somente documentos cujo prazo de 60 dias venceu aparecem aqui. A remoção apaga o arquivo e preserva o registro textual da validação.</p>{purge.length===0?<p>Nenhum documento aguardando expurgo.</p>:purge.map(d=><div className="admin-summary" key={d.id}><strong>{d.cataloging_requests?.protocol??d.request_id}</strong><span>Prazo: {new Date(d.purge_after).toLocaleString("pt-BR")}</span><button className="button button--danger button--small" disabled={busy===`x-${d.id}`} onClick={()=>purgeFile(d)}>Expurgar arquivo</button></div>)}</section>
  <section className="panel admin-section"><p className="eyebrow">Auditoria</p><h2>Logs operacionais e administrativos</h2><div className="audit-table">{props.logs.map(l=><article key={l.id}><time>{new Date(l.occurred_at).toLocaleString("pt-BR")}</time><strong>{actionLabels[l.action]??l.action}</strong><span>{l.profiles?.full_name??"Sistema"} · {l.entity_type}{l.entity_id?` · ${l.entity_id}`:""}</span></article>)}</div></section>
  <section className="panel admin-section"><p className="eyebrow">Conteúdo público</p><h2>Perguntas frequentes</h2><p>Edite as respostas públicas, desative itens temporariamente ou acrescente novas perguntas.</p><div className="admin-list">{faqs.map(faq=><form className="admin-row admin-row--faq" action={form=>saveFaq(faq,form)} key={faq.id||"new"}><label>Pergunta<input name="question" required minLength={5} maxLength={300} defaultValue={faq.question}/></label><label className="admin-wide">Resposta<textarea name="answer" required minLength={5} maxLength={4000} rows={3} defaultValue={faq.answer}/></label><label>Ordem<input name="position" type="number" min="0" max="9999" defaultValue={faq.position}/></label><label className="compact-check"><input name="active" type="checkbox" defaultChecked={faq.active}/> Publicada</label><button className="button button--secondary button--small" disabled={busy===`f-${faq.id||"new"}`}>Salvar</button></form>)}</div><button className="button button--primary button--small" type="button" onClick={()=>setFaqs(current=>[...current,{id:"",question:"",answer:"",position:(Math.max(0,...current.map(item=>item.position))+10),active:true}])}>Adicionar pergunta</button></section>
 </div>;
}
function Metric({title,items}:{title:string;items:StatItem[]}){return <div><h3>{title}</h3>{items.map(x=><div className="metric-row" key={`${x.id}-${x.label}`}><span>{x.label}</span><strong>{x.count}</strong></div>)}</div>}
