"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import { AppIcon } from "./app-icon";
import { HelpSearch } from "./help-search";
import type { KnowledgeItem } from "@/lib/knowledge-base";
type HelpContext = "administracao" | "atendimento" | "estudante" | "painel";
const labels: Record<HelpContext, string> = { administracao: "Administração", atendimento: "Atendimento", estudante: "Sua solicitação", painel: "Painel" };
export function BackendHelpWidget({ role }: { role: string }) {
  const pathname = usePathname(); const [open, setOpen] = useState(false); const [items, setItems] = useState<KnowledgeItem[]>([]); const [activeContext, setActiveContext] = useState<HelpContext>("painel"); const [history, setHistory] = useState<HelpContext[]>([]); const [selected, setSelected] = useState<KnowledgeItem | null>(null);
  const pageContext: HelpContext = pathname.includes("/admin") ? "administracao" : pathname.includes("/atendimento") || pathname.includes("/fila") ? "atendimento" : role === "student" ? "estudante" : "painel";
  useEffect(() => { if (!open) return; setActiveContext((previous) => { if (previous !== pageContext) setHistory((entries) => [previous, ...entries.filter((entry) => entry !== previous)].slice(0, 4)); return pageContext; }); setSelected(null); }, [open, pageContext]);
  useEffect(() => { if (!open) return; fetch(`/api/central-de-duvidas?context=${activeContext}`).then((response) => response.ok ? response.json() : { results: [] }).then(({ results }) => setItems(results)); }, [activeContext, open]);
  const reopen = (context: HelpContext) => { setActiveContext(context); setHistory((entries) => entries.filter((entry) => entry !== context)); setSelected(null); };
  return <div className={`backend-help${open ? " is-open" : ""}`}><button className="backend-help__trigger" type="button" onClick={() => setOpen((value) => !value)} aria-expanded={open} aria-controls="ajuda-contextual" aria-label="Abrir ajuda contextual" title="Ajuda contextual"><AppIcon name="help" /><span>Precisa de ajuda?</span></button>{open && <section className="backend-help__panel" id="ajuda-contextual" aria-label="Ajuda contextual"><header><div><p className="eyebrow">Ajuda para {labels[activeContext]}</p><h2>{selected ? selected.title : "Como podemos ajudar?"}</h2></div><button className="backend-help__close" type="button" onClick={() => setOpen(false)} aria-label="Fechar ajuda contextual"><AppIcon name="close" /></button></header>{selected ? <div className="backend-help__answer">{selected.bodyHtml ? <div className="knowledge-rich-content" dangerouslySetInnerHTML={{ __html: selected.bodyHtml }} /> : <p>{selected.summary}</p>}<button type="button" onClick={() => setSelected(null)}>Voltar para as sugestões</button></div> : <><HelpSearch compact context={activeContext} onAnswerSelect={setSelected} openArticlesInNewTab />{items.length > 0 && <div className="backend-help__topics"><strong>Mais útil nesta tela</strong>{items.slice(0, 3).map((item) => item.slug ? <Link key={item.id} href={`/ajuda/artigos/${item.slug}`} target="_blank" rel="noreferrer">{item.title}<AppIcon name="external" /></Link> : <button key={item.id} type="button" onClick={() => setSelected(item)}>{item.title}</button>)}</div>}{history.length > 0 && <div className="backend-help__history"><strong>Contextos anteriores</strong>{history.map((context) => <button key={context} type="button" onClick={() => reopen(context)}>Reabrir ajuda: {labels[context]}</button>)}</div>}<Link className="backend-help__all" href="/ajuda" target="_blank" rel="noreferrer">Abrir Central de ajuda <AppIcon name="external" /></Link></>}</section>}</div>;
}
