"use client";

import { useState } from "react";
import fontkit from "@pdf-lib/fontkit";
import { PDFDocument, StandardFonts } from "pdf-lib";
import { A4_PAGE, drawCatalogingCard } from "@/domain/cataloging-card/pdf";
import type { CatalogingCardSnapshot } from "@/domain/cataloging-card/types";

export function BrowserPdfDelivery({ snapshot }: { snapshot: CatalogingCardSnapshot }) {
  const [workFile,setWorkFile]=useState<File|null>(null);const [fontFile,setFontFile]=useState<File|null>(null);const [titlePage,setTitlePage]=useState(1);const [confirmed,setConfirmed]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function generate(merge:boolean){setBusy(true);setError("");try{const document=merge?await loadWork():await PDFDocument.create();if(!merge)document.addPage(A4_PAGE);document.registerFontkit(fontkit);const regular=fontFile?await document.embedFont(await fontFile.arrayBuffer(),{subset:true}):await document.embedFont(StandardFonts.Helvetica);const bold=fontFile?regular:await document.embedFont(StandardFonts.HelveticaBold);let page;if(merge){const pages=document.getPageCount();if(!Number.isInteger(titlePage)||titlePage<1||titlePage>pages)throw new Error(`Informe uma folha de rosto entre 1 e ${pages}.`);page=document.insertPage(titlePage,A4_PAGE);}else page=document.getPage(0);drawCatalogingCard(page,snapshot,{regular,bold});const bytes=await document.save();download(bytes,merge?`trabalho-com-ficha-${snapshot.request.protocol}.pdf`:`ficha-${snapshot.request.protocol}.pdf`);}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível processar o PDF selecionado.");}finally{setBusy(false);}}
  async function loadWork(){if(!workFile)throw new Error("Selecione o PDF completo do trabalho.");if(!workFile.name.toLowerCase().endsWith(".pdf")||workFile.type!=="application/pdf")throw new Error("O trabalho precisa ser um arquivo PDF.");return PDFDocument.load(await workFile.arrayBuffer());}
  return <section className="panel browser-pdf-delivery"><div><p className="eyebrow">Processamento local</p><h2>Gerar trabalho completo com ficha</h2><p>Seu trabalho e a fonte escolhida permanecem somente neste navegador e não são enviados ao Pronto!.</p></div><div className="document-warning"><strong>Use exatamente o arquivo analisado pela biblioteca.</strong><p>Se você escolher uma versão diferente, o trabalho resultante poderá ficar documentalmente inconsistente com os metadados e declarações já aprovados.</p></div><label>PDF completo do trabalho<input type="file" accept="application/pdf,.pdf" onChange={(event)=>{setWorkFile(event.target.files?.[0]??null);setConfirmed(false);setError("");}} /></label>{workFile&&<div className="selected-file"><strong>{workFile.name}</strong><span>{formatBytes(workFile.size)}</span></div>}<label className="check"><input type="checkbox" checked={confirmed} onChange={(event)=>setConfirmed(event.target.checked)} /> Declaro que este é o mesmo arquivo analisado pela biblioteca, finalizado e com folha de aprovação.</label><label>Página da folha de rosto<input type="number" min={1} step={1} value={titlePage} onChange={(event)=>setTitlePage(Number(event.target.value))} /></label><p className="field-hint">A ficha será inserida em uma nova página imediatamente depois da folha de rosto indicada.</p><label>Fonte local opcional — TTF ou OTF<input type="file" accept=".ttf,.otf,font/ttf,font/otf" onChange={(event)=>setFontFile(event.target.files?.[0]??null)} /></label>{fontFile&&<div className="selected-file"><strong>{fontFile.name}</strong><span>Usada somente durante esta geração local</span></div>}<div className="pdfa-guidance"><strong>Sobre PDF/A</strong><p>O navegador gera um PDF comum, mas não certifica conformidade PDF/A. Antes do autodepósito, confira ou converta o arquivo final conforme a exigência do Repositório Institucional.</p></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="delivery-actions"><button className="button button--primary" type="button" disabled={!workFile||!confirmed||busy} onClick={()=>generate(true)}>{busy?"Processando no navegador…":"Gerar e baixar trabalho completo com ficha"}</button><button className="link-button" type="button" disabled={busy} onClick={()=>generate(false)}>Baixar somente a ficha</button></div></section>;
}

function download(bytes:Uint8Array,name:string){const blob=new Blob([new Uint8Array(bytes)],{type:"application/pdf"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
function formatBytes(value:number){return value<1024*1024?`${(value/1024).toFixed(1)} KB`:`${(value/1024/1024).toFixed(2)} MB`;}
