"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { FinalDecisionDialog } from "@/components/final-decision-dialog";

export function NadaConstaReview({ document, editable }: { document: { id: string; object_path: string | null; original_name: string; size_bytes: number; status: string; rejection_reason: string | null; validated_at: string | null } | null; editable: boolean }) {
  const router = useRouter(); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [confirmingDecision, setConfirmingDecision] = useState<"approve" | "return" | null>(null);
  async function openDocument() { if (!document?.object_path) return; const supabase=createClient(); const { data,error:signError }=await supabase.storage.from("nada-consta").createSignedUrl(document.object_path,60); if(signError||!data){setError("Não foi possível abrir o documento privado.");return;} window.open(data.signedUrl,"_blank","noopener,noreferrer"); }
  async function validate(approved: boolean) { if(!document)return; setBusy(true);setError("");const supabase=createClient();const { data:path,error:validationError }=await supabase.rpc("validate_nada_consta",{target_document_id:document.id,approved,reason:approved?null:reason});if(validationError){setError("Não foi possível registrar a validação.");setBusy(false);return;}if(!approved&&path){const { error:removeError }=await supabase.storage.from("nada-consta").remove([path]);if(removeError){setError("A devolução foi registrada, mas o arquivo privado não pôde ser removido. Avise o administrador antes do reenvio.");setBusy(false);return;}}router.refresh(); }
  async function confirmDecision() { if (!confirmingDecision) return; await validate(confirmingDecision === "approve"); setConfirmingDecision(null); }
  return <section className="panel nada-consta-panel"><div><p className="eyebrow">Nada Consta e liberação</p><h2>Nada Consta</h2><p>A validação pode ocorrer antes ou depois da homologação. A ficha será liberada somente quando as duas aprovações existirem.</p></div>{!document ? <p><strong>Liberação bloqueada:</strong> o estudante ainda não enviou o documento.</p> : <><div className={`document-state document-state--${document.status}`}><strong>{document.status==="pending"?"Aguardando validação":document.status==="approved"?"Aprovado":"Devolvido"}</strong><span>{document.original_name} · {(document.size_bytes/1024/1024).toFixed(2)} MB</span>{document.validated_at&&<small>Validado em {new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(document.validated_at))}</small>}</div><button className="button button--secondary button--small" type="button" onClick={openDocument}>Abrir PDF privado</button>{document.status==="pending"&&editable&&<div className="nada-consta-actions"><label>Justificativa da devolução<textarea rows={3} maxLength={2000} value={reason} onChange={(event)=>setReason(event.target.value)} placeholder="Obrigatória somente ao devolver" /></label><div><button className="button button--danger" disabled={busy||reason.trim().length<3} onClick={()=>setConfirmingDecision("return")}>Devolver documento</button><button className="button button--primary" disabled={busy} onClick={()=>setConfirmingDecision("approve")}>Aprovar Nada Consta</button></div></div>}</>}{error&&<p className="form-error" role="alert">{error}</p>}{confirmingDecision&&<FinalDecisionDialog title={confirmingDecision==="approve"?"Aprovar o Nada Consta?":"Devolver o Nada Consta?"} description={confirmingDecision==="approve"?"O documento será validado e poderá liberar a ficha assim que a homologação também existir.":"O documento será devolvido ao estudante com a justificativa informada."} confirmLabel={confirmingDecision==="approve"?"Confirmar aprovação":"Confirmar devolução"} confirmDanger={confirmingDecision==="return"} busy={busy} onCancel={()=>setConfirmingDecision(null)} onConfirm={confirmDecision}/>}</section>;
}
