import { ProtectedEmail } from "./protected-email";

export function PrivacyNoticeContent({ compact = false }: { compact?: boolean }) {
  return <div className={compact ? "privacy-notice-text privacy-notice-text--compact" : "privacy-notice-text"}>
    <section><h2>1. Dados e finalidade</h2><p>Podemos tratar nome, e-mail institucional, CPF, data de nascimento, matrícula ou vínculo acadêmico, dados da solicitação, link público do trabalho e informações do atendimento. Senhas não são visíveis para a biblioteca.</p><p>Usamos esses dados para identificar a pessoa usuária, manter a conta segura, receber e atender a solicitação de ficha, orientar o autodepósito e registrar ações necessárias à continuidade do serviço. A data completa fica salva na conta. Ao solicitar a ficha, o estudante pode autorizar o uso apenas do ano de nascimento para diferenciar pessoas com o mesmo nome. Sem essa autorização, o ano não é usado na ficha. Mesmo com autorização, a biblioteca confere o ano antes de incluí-lo.</p></section>
    <section><h2>2. Responsáveis, base legal e contato</h2><p><strong>Controladora:</strong> Universidade Federal da Bahia (UFBA), por meio da Biblioteca da Faculdade de Arquitetura.</p><p><strong>Canal do serviço:</strong> <ProtectedEmail recipient="library" />. <strong>Encarregada de Dados da UFBA:</strong> Ana Cláudia Caldas Mendonça Semêdo; canal institucional: <ProtectedEmail recipient="privacy" />.</p><p>Informações institucionais sobre proteção de dados estão disponíveis na <a href="https://lgpd.ufba.br/" target="_blank" rel="noreferrer">página de LGPD da UFBA</a>.</p><p>O tratamento fundamenta-se no cumprimento de obrigação legal ou regulatória e atende à finalidade pública de prestar o serviço bibliotecário da UFBA.</p></section>
    <section><h2>3. Seus direitos</h2><p>Você pode confirmar o tratamento, acessar e corrigir seus dados; pedir anonimização, bloqueio ou eliminação quando cabível; conhecer compartilhamentos; pedir portabilidade quando aplicável; peticionar à ANPD e opor-se a tratamento irregular.</p><p>Alguns pedidos dependem da finalidade pública, das obrigações legais e das regras de conservação. A Ouvidoria orienta o atendimento.</p></section>
    <section><h2>4. Acesso, compartilhamento e cookies</h2><p>Você acessa seus próprios dados. A equipe autorizada vê apenas o necessário para atender a solicitação. A coordenação, quando habilitada, recebe visão limitada, sem CPF, documentos ou comentários internos.</p><p>Supabase (autenticação, banco e armazenamento) e Vercel (hospedagem) atuam como operadores técnicos. O Pronto! não vende dados nem os utiliza para marketing.</p><p>Cookies essenciais mantêm a sessão. O navegador pode guardar preferência de tema e rascunho local. Não usamos cookies de publicidade ou ferramentas próprias de análise de navegação.</p></section>
    <section><h2>5. Proteção e prazos de guarda</h2><p>Usamos conexão protegida, autenticação, controle por perfil e registros de ações para reduzir riscos. Conta, CPF, data de nascimento, e-mail e o atendimento acadêmico são mantidos enquanto houver vínculo e, no total, por 100 anos, como assentamento individual do aluno. Solicitação, metadados, ficha, pendências e homologação seguem o mesmo prazo.</p><p>O Nada Consta no Pronto! é apenas arquivo de conferência e é removido 60 dias após o encerramento; o registro de longo prazo permanece no Pergamum. Auditorias administrativas e operacionais: 5 anos; logs técnicos: 6 meses; incidentes: 5 anos após apuração; backups: 90 dias, salvo preservação necessária.</p></section>
  </div>;
}
