"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export function ProtocolClosure({ requestId, coordinationEnabled, ready }: { requestId: string; coordinationEnabled: boolean; ready: boolean }) {
  const router=useRouter(); const [url,setUrl]=useState(""); const [link,setLink]=useState(""); const [busy,setBusy]=useState(""); const [message,setMessage]=useState("");
  async function issueLink(){setBusy("link");setMessage("");const {data,error}=await createClient().rpc("issue_coordination_magic_link",{target_request_id:requestId});if(error)setMessage("Não foi possível gerar o acesso. Confira a configuração da coordenação e a responsabilidade pelo atendimento.");else {const value=`${window.location.origin}/coordenacao/${data}`;setLink(value);await navigator.clipboard.writeText(value);setMessage("Magic Link gerado e copiado. Ele será inutilizado no encerramento.");}setBusy("");}
  async function close(){setBusy("close");setMessage("");const {error}=await createClient().rpc("close_cataloging_request",{target_request_id:requestId,permanent_url:url.trim()});if(error){setMessage("Não foi possível encerrar. Confirme o endereço HTTPS e se ficha, Nada Consta e autodepósito estão registrados.");setBusy("");return;}router.refresh();}
  return <section className="panel protocol-closure"><p className="eyebrow">Encerramento</p><h2>Verificação da publicação no RI/UFBA</h2><p>Abra o registro no repositório, confirme a publicação e informe abaixo o endereço permanente ou Handle.</p>{coordinationEnabled&&<div className="coordination-access"><strong>Acompanhamento da coordenação</strong><p>O acesso é somente leitura e não mostra CPF, documentos ou comentários internos.</p><button className="button button--secondary button--small" disabled={busy!==""} onClick={issueLink}>{busy==="link"?"Gerando…":"Gerar e copiar Magic Link"}</button>{link&&<input aria-label="Magic Link da coordenação" readOnly value={link}/>}</div>}<label>URL permanente ou Handle<input type="url" required placeholder="https://repositorio.ufba.br/handle/…" value={url} onChange={(event)=>setUrl(event.target.value)} /></label>{!ready&&<p className="form-hint">Antes do encerramento, devem estar registrados: ficha homologada, Nada Consta aprovado e início do autodepósito.</p>}<button className="button button--primary" disabled={!ready||busy!==""||!url.startsWith("https://")} onClick={close}>{busy==="close"?"Encerrando…":"Verifiquei no RI/UFBA e quero encerrar"}</button>{message&&<p className="auth-feedback" role="status">{message}</p>}</section>;
}
