"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Program = { id: string; name: string; level: string; repository_deposit_enabled: boolean; repository_collection_label: string | null; coordination_magic_link_enabled: boolean; coordination_contacts: {name:string;email:string;active:boolean}[] };
export function RepositoryProgramSettings({ programs }: { programs: Program[] }) {
  const [items,setItems]=useState(programs); const [busy,setBusy]=useState(""); const [message,setMessage]=useState("");
  async function toggle(program: Program) { setBusy(program.id); setMessage(""); const enabled=!program.repository_deposit_enabled; const { error }=await createClient().rpc("set_repository_deposit_enabled",{target_program_id:program.id,enabled}); if(error)setMessage("Não foi possível alterar a configuração."); else {setItems((current)=>current.map((item)=>item.id===program.id?{...item,repository_deposit_enabled:enabled}:item));setMessage("Configuração salva e registrada no log.");} setBusy(""); }
  async function configureCoordination(program:Program,form:FormData){setBusy(`coord-${program.id}`);setMessage("");const enabled=form.get("enabled")==="on";const name=String(form.get("name")??"");const email=String(form.get("email")??"");const {error}=await createClient().rpc("configure_program_coordination",{target_program_id:program.id,enabled,contact_name:name,contact_email:email});if(error)setMessage("Não foi possível salvar a coordenação. Quando ativa, informe nome e e-mail válidos.");else{setItems(current=>current.map(item=>item.id===program.id?{...item,coordination_magic_link_enabled:enabled,coordination_contacts:enabled?[{name,email,active:true}]:[]}:item));setMessage("Configuração da coordenação salva e registrada no log.");}setBusy("");}
  return <section className="program-settings">{message&&<p className="auth-feedback" role="status">{message}</p>}{items.map((program)=>{const contact=program.coordination_contacts.find(item=>item.active);return <article className="panel program-setting-card" key={program.id}><div><span>{program.level}</span><h2>{program.name}</h2><p>{program.repository_collection_label ?? "Coleção do RI ainda não configurada."}</p><button className={`button button--small ${program.repository_deposit_enabled?"button--secondary":"button--primary"}`} disabled={busy===program.id} onClick={()=>toggle(program)}>{program.repository_deposit_enabled?"Desativar guia":"Ativar guia"}</button></div><form action={(form)=>configureCoordination(program,form)}><strong>Magic Link da coordenação</strong><label><input type="checkbox" name="enabled" defaultChecked={program.coordination_magic_link_enabled}/> Ativar acompanhamento</label><label>Nome do contato<input name="name" defaultValue={contact?.name??""}/></label><label>E-mail institucional<input name="email" type="email" defaultValue={contact?.email??""}/></label><button className="button button--secondary button--small" disabled={busy===`coord-${program.id}`}>Salvar coordenação</button></form></article>})}</section>;
}
