update public.knowledge_base_entries
set body_html = $article$
<section class="knowledge-card knowledge-card--info"><h2><span class="knowledge-card__icon" aria-hidden="true">☁</span>Antes de compartilhar</h2><p>Use o PDF final do trabalho e compartilhe somente esse arquivo, ou uma pasta criada apenas para ele. Um link público permite que qualquer pessoa que o receba abra o conteúdo; não compartilhe uma pasta com outros documentos.</p></section>
<section class="knowledge-card knowledge-card--allowed"><h2><span class="knowledge-card__icon" aria-hidden="true">✓</span>Permissões corretas</h2><p>Permita o acesso a qualquer pessoa com o link e escolha somente visualização. Teste o endereço em uma janela privada antes de informá-lo no formulário.</p></section>
<section class="knowledge-card knowledge-card--prohibited"><h2><span class="knowledge-card__icon" aria-hidden="true">×</span>Evite estas configurações</h2><p>Não use convite limitado ao seu e-mail ou à UFBA. Não permita edição. Não configure senha, código ou prazo de expiração para o link. Se a organização bloquear o compartilhamento público, use outro serviço permitido.</p></section>
<section class="knowledge-card knowledge-card--info"><h2><span class="knowledge-card__icon" aria-hidden="true">☁</span>Google Drive</h2><ol class="knowledge-steps"><li><p>Selecione o PDF e clique em Compartilhar.</p></li><li><p>Em Acesso geral, abra a lista de permissões e escolha Qualquer pessoa com o link.</p></li><li><p>Defina o papel como Leitor (Viewer), sem permissão de edição.</p></li><li><p>Clique em Copiar link e depois em Concluído.</p></li></ol><p class="knowledge-card__link"><a href="https://support.google.com/docs/answer/2494822?hl=pt-BR">Instruções oficiais do Google Drive</a></p></section>
<section class="knowledge-card knowledge-card--info"><h2><span class="knowledge-card__icon" aria-hidden="true">☁</span>Microsoft OneDrive</h2><ol class="knowledge-steps"><li><p>Selecione o PDF e clique em Compartilhar.</p></li><li><p>Abra as configurações do link (ícone de engrenagem) e escolha Qualquer pessoa.</p></li><li><p>Desative Permitir edição; mantenha somente visualização.</p></li><li><p>Clique em Aplicar e depois em Copiar link.</p></li></ol><p>Em contas institucionais, a opção Qualquer pessoa pode estar bloqueada pelo administrador. Se não aparecer, escolha outro serviço permitido.</p><p class="knowledge-card__link"><a href="https://support.microsoft.com/en-us/onedrive/share-files-and-folders-in-onedrive">Instruções oficiais do OneDrive</a></p></section>
<section class="knowledge-card knowledge-card--info"><h2><span class="knowledge-card__icon" aria-hidden="true">☁</span>Dropbox</h2><ol class="knowledge-steps"><li><p>Passe o cursor sobre o PDF e clique em Compartilhar.</p></li><li><p>Clique em Copiar link e abra Gerenciar (Manage) nas opções do link.</p></li><li><p>Escolha Link para visualização (Link for viewing), sem edição.</p></li><li><p>Copie o link de visualização.</p></li></ol><p class="knowledge-card__link"><a href="https://help.dropbox.com/share/create-and-share-link">Instruções oficiais do Dropbox</a></p></section>
<section class="knowledge-card knowledge-card--info"><h2><span class="knowledge-card__icon" aria-hidden="true">☁</span>iCloud Drive</h2><ol class="knowledge-steps"><li><p>No iCloud Drive, abra o menu do PDF e escolha Compartilhar.</p></li><li><p>Em quem pode acessar, escolha Qualquer pessoa com o link.</p></li><li><p>Em permissões, escolha Somente visualizar e baixar.</p></li><li><p>Crie o link e clique em Copiar link.</p></li></ol><p class="knowledge-card__link"><a href="https://support.apple.com/guide/icloud/mm708256356b/icloud">Instruções oficiais do iCloud Drive</a></p></section>
<section class="knowledge-card knowledge-card--info"><h2><span class="knowledge-card__icon" aria-hidden="true">☁</span>Proton Drive</h2><ol class="knowledge-steps"><li><p>Selecione o PDF e clique no ícone Compartilhar.</p></li><li><p>Ative Criar link público (Create public link).</p></li><li><p>Escolha Visualizador (Viewer), não Editor.</p></li><li><p>Clique em Copiar link.</p></li></ol><p>Não ative senha ou data de expiração: a biblioteca precisa conseguir abrir o arquivo pelo link.</p><p class="knowledge-card__link"><a href="https://proton.me/support/drive-shareable-link">Instruções oficiais do Proton Drive</a></p></section>
<section class="knowledge-card knowledge-card--info"><h2><span class="knowledge-card__icon" aria-hidden="true">☁</span>Nextcloud</h2><ol class="knowledge-steps"><li><p>Na lista de arquivos, selecione o PDF e abra Compartilhar.</p></li><li><p>Crie um link público (public link).</p></li><li><p>Escolha Somente leitura (read only), sem edição ou envio de arquivos.</p></li><li><p>Copie o link público.</p></li></ol><p>As opções variam conforme a configuração do servidor Nextcloud. Se o compartilhamento por link estiver desativado, contate o administrador ou use outro serviço permitido.</p><p class="knowledge-card__link"><a href="https://docs.nextcloud.com/server/stable/user_manual/en/files/sharing.html">Manual oficial do Nextcloud sobre compartilhamento</a></p></section>
<section class="knowledge-card knowledge-card--allowed"><h2><span class="knowledge-card__icon" aria-hidden="true">✓</span>Teste o link antes de enviar</h2><ol class="knowledge-steps"><li><p>Abra uma janela anônima ou privada do navegador, sem entrar na conta do serviço.</p></li><li><p>Cole o link e confirme que o PDF abre sem pedir login, autorização, senha ou código enviado por e-mail.</p></li><li><p>Confira se o PDF exibido é a versão final e está completo.</p></li><li><p>Volte ao formulário, cole o endereço iniciado por https:// no campo Link público do trabalho completo e envie a solicitação.</p></li></ol></section>
<section class="knowledge-card knowledge-card--warning"><h2><span class="knowledge-card__icon" aria-hidden="true">!</span>Se o teste falhar</h2><p>Revise as permissões e gere um novo link. Não envie um endereço que abra somente para você, que peça autorização, ou que dependa de uma senha privada. O Pronto! recebe apenas o link; o PDF completo não é enviado nem armazenado pelo sistema.</p></section>
$article$,
updated_at = now()
where slug = 'compartilhar-link-publico';
