import type { AcademicProgramSeed } from "./types";

export const initialAcademicPrograms = [
  {
    code: "architecture-urbanism-undergraduate",
    name: "Bacharelado em Arquitetura e Urbanismo",
    shortName: "Arquitetura e Urbanismo",
    level: "undergraduate",
    workType: "undergraduate_thesis",
    repositoryDepositEnabled: false,
    repositoryDocumentTypeLabel: "Trabalho de Conclusão de Curso",
    repositoryAcademicDegreeLabel: "Bacharelado",
    repositoryCollectionLabel: "Faculdade de Arquitetura > Trabalho de Conclusão de Curso (Graduação) - Arquitetura (Faculdade de Arquitetura)",
  },
  {
    code: "athdc-specialization",
    name: "Especialização em Assistência Técnica, Habitação e Direito à Cidade",
    shortName: "Especialização ATHDC",
    level: "specialization",
    workType: "specialization_thesis",
    repositoryDepositEnabled: true,
    repositoryDocumentTypeLabel: "Trabalho de Conclusão de Curso",
    repositoryAcademicDegreeLabel: "Especialização",
    repositoryCollectionLabel: "Faculdade de Arquitetura > Programa de Pós-Graduação em Arquitetura e Urbanismo (AUE) > Trabalho de Conclusão de Curso (Especialização) - Assistência Técnica, Habitação e Direito à Cidade (AUE)",
  },
  {
    code: "mp-cecre-master",
    name: "Mestrado Profissional em Conservação e Restauração de Monumentos e Núcleos Históricos",
    shortName: "MP/CECRE",
    level: "master",
    workType: "dissertation",
    repositoryDepositEnabled: true,
    repositoryDocumentTypeLabel: "Dissertação",
    repositoryAcademicDegreeLabel: "Mestrado Profissional",
    repositoryCollectionLabel: "Faculdade de Arquitetura > Mestrado Profissional em Conservação e Restauração de Monumentos e Núcleos Históricos (MP/CECRE) > Dissertação (MP/CECRE)",
  },
  {
    code: "ppgau-academic-master",
    name: "Mestrado em Arquitetura e Urbanismo",
    shortName: "Mestrado PPGAU",
    level: "master",
    workType: "dissertation",
    repositoryDepositEnabled: true,
    repositoryDocumentTypeLabel: "Dissertação",
    repositoryAcademicDegreeLabel: "Mestrado Acadêmico",
    repositoryCollectionLabel: "Faculdade de Arquitetura > Programa de Pós-Graduação em Arquitetura e Urbanismo (PPGAU) > Dissertação (PPGAU)",
  },
  {
    code: "ppgau-doctorate",
    name: "Doutorado em Arquitetura e Urbanismo",
    shortName: "Doutorado PPGAU",
    level: "doctorate",
    workType: "thesis",
    repositoryDepositEnabled: true,
    repositoryDocumentTypeLabel: "Tese",
    repositoryAcademicDegreeLabel: "Doutorado",
    repositoryCollectionLabel: "Faculdade de Arquitetura > Programa de Pós-Graduação em Arquitetura e Urbanismo (PPGAU) > Tese (PPGAU)",
  },
] as const satisfies readonly AcademicProgramSeed[];
